# -*- coding: utf-8 -*-
"""AI-Agent-101.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mNy99PxTOMncjEQlVfJuQGTB3tjtWYYd
"""

!pip install -qU crewai[tools,agentops]==0.95.0

!pip install -qU tavily-python scrapegraph-py

from crewai import Agent, Task, Crew, Process, LLM
from crewai.tools import tool
from crewai.knowledge.source.string_knowledge_source import StringKnowledgeSource
import agentops
from google.colab import userdata
from pydantic import BaseModel, Field
from typing import List
from tavily import TavilyClient
from scrapegraph_py import Client

import os
import json

os.environ["OPENAI_API_KEY"] = userdata.get('openai-colab')
os.environ["AGENTOPS_API_KEY"] = userdata.get('agentops-colab')

agentops.init(
    api_key=userdata.get('agentops-colab'),
    skip_auto_end_session=True
)

output_dir = "./ai-agent-output"
os.makedirs(output_dir, exist_ok=True)

basic_llm = LLM(model="gpt-4o", temperature=0)

# 1) Agent
search_queries_recommender_agent = Agent(
    role="search-queries-recommender-agent", # The role of the agent short description of the agent's purpose (e.g. "weather-forecast-agent")
    goal="""To provide a list of suggested serache aueries to be passed to the seacr engine.
            the queries must be varied and looking for specific items.""", # The goal of the agent (what it is supposed to do)

    backstory="The agent is designed to help in looking for products by providing a list of suggested search queries to be passed to the search engine based on the context provided.", # The backstory of the agent (the reason for its existence)
    llm=basic_llm, # The language model to be used by the agent
    verbose=True, # Whether to print the agent's interactions
)


search_queries_recommender_task = Task(
    description="""
    Rankyx is looking to buy {product_name} at the best prices (value for a price strategy).
    The campany target any of these websites to buy from: {websites_list}.
    The company wants to reach all available proucts on the internet to be compared later in another stage.
    The stores must sell the product in {country_name}.
    Generate at maximum {num_of_keywords} queries.
    The search keywords must be in {language} language.
    Search keywords must contains specific brands, types or technologies. Avoid general keywords.
    The search query must reach an ecommerce webpage for product, and not a blog or listing page.
""" # The description of the task to be performed by the agent (what it is supposed to do)

)